### ISSUE TITLE
Mention operator is not supported or prioritized

### ISSUE THREAD

**Issue by brandonkal** [openfaas/openfaas-operator#112]
From my conversation on Slack, I came to realize installing/testing the operator is discouraged and resources are not available to maintain this. Others may find this information useful in the README. I had previously thought this was planned to supersede the other approach on Kubernetes.

**Comment by alexellis** [comment]
This is not the case, I am not sure how you came to believe this to be true.

The operator is not currently supported in OpenFaaS Cloud when using ofc-bootstrap.
