### ISSUE TITLE
Unexpected status: 500, message: Function.openfaas.com "<SOME_FUNCTION>" is invalid

### ISSUE THREAD

**Issue by joelcorporan** [openfaas/openfaas-operator#114]
I'm following a the tutorial for running OpenFaaS on AWS (https://aws.amazon.com/blogs/opensource/deploy-openfaas-aws-eks/) and deploying the function on that tutorial. However, I'm having issues deploying a function. I'd get a 500 message.

## Expected Behaviour
```
faas-cli up -f hello-python.yml
```
200 Status

## Current Behaviour
```
faas-cli up -f hello-python.yml
```
```
Deploying: hello-python.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Unexpected status: 500, message: Function.openfaas.com "hello-python" is invalid: []: Invalid value: map[string]interface {}{"apiVersion":"openfaas.com/v1", "kind":"Function", "metadata":map[string]interface {}{"creationTimestamp":"2020-03-16T17:22:09Z", "generation":1, "name":"hello-python", "namespace":"openfaas-fn", "uid":"aa8bf881-67aa-11ea-b165-16d96eae1e15"}, "spec":map[string]interface {}{"annotations":map[string]interface {}{}, "constraints":interface {}(nil), "environment":map[string]interface {}{}, "handler":"python index.py", "image":"corporan/hello-python:latest", "labels":map[string]interface {}{}, "limits":interface {}(nil), "name":"hello-python", "readOnlyRootFilesystem":false, "requests":interface {}(nil), "secrets":[]interface {}{}}}: validation failure list:
spec.constraints in body must be of type array: "null"

Function 'hello-python' failed to deploy with status code: 500
```
## Your Environment

* FaaS-CLI version 0.11.8
* Docker version 19.03.8
* Kubernetes (FaaS-netes)
* MacOS 10.14.6

**Comment by alexellis** [comment]
I was able to reproduce this issue with the following:

```
arkade install openfaas --operator
```

And:

```
faas-cli new --lang python3 tester-issue --prefix alexellis2
faas-cli up -f tester.issue.yml
```

Output:

```
[0] < Pushing tester-issue [alexellis2/tester-issue:latest] done.
[0] Worker done.

Deploying: tester-issue.
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Unexpected status: 500, message: Function.openfaas.com "tester-issue" is invalid: spec.constraints: Invalid value: "null": spec.constraints in body must be of type array: "null"

Function 'tester-issue' failed to deploy with status code: 500
```

**Comment by alexellis** [comment]
@stefanprodan @LucasRoesler PTAL

**Comment by alexellis** [comment]
@joelcorporan we'll take a look at this, in the meantime, you can work without the operator and use the same guide to install and use openfaas.

**Comment by jrcichra** [comment]
Is this still an issue? I got a similar message with the latest KinD and a python3 stock function.

Later today I'll see if I can reproduce the issue, maybe in a small github actions CI repo with a matrixed KinD version. Then I can look into a PR for testing.

**Comment by jrcichra** [comment]
Ah, noticed the reference. Linking for Googlers: https://github.com/openfaas/openfaas-operator/issues/117

**Comment by alexellis** [comment]
No, it's not an issue anymore AFAIK. @stefanprodan sent a PR which was merged and released. 

Could you please raise your own issue on the faas-netes repo with all the instructions we will require to reproduce the issue?

**Comment by alexellis** [comment]
/lock: resolved by a PR, raise a new issue for subsequent issues
