### ISSUE TITLE
Min replica missing from CRD loop

### ISSUE THREAD

**Issue by jpds** [openfaas/openfaas-operator#74]
## Expected Behaviour

As per https://github.com/openfaas/faas-netes/issues/390 - the min replica value is not respected in the CRD loop.

**Comment by alexellis** [comment]
@stefanprodan @lucasroesler is anyone looking at this?

**Comment by LucasRoesler** [comment]
I can take a stab at this.  Looking through the code, it seems like it could be a one line change:

https://github.com/openfaas-incubator/openfaas-operator/blob/0a101ece8ea05d235ea02750de7e3e3e4af49b76/pkg/controller/deployment.go#L57

We can modify it to set Replicas to `max(function.Spec.Replicas, getMinReplicaCount(function.Spec.Labels)`

As far as I can tell, `newDeployment` is used to construct the `Deployment` during both create and update, so this one change should reflect the desired behavior of not scaling below the specified min.  In fact, we probably need something like 

```go
min(
    getMaxReplicaCount(function.Spec.Labels),
    max(function.Spec.Replicas, getMinReplicaCount(function.Spec.Labels),
)
```

To ensure that we don't go over the max. 

`getMaxReplicaCount` would need to be implemented. Given our docs on max/min replicas, https://docs.openfaas.com/architecture/autoscaling/#minmax-replicas, it would return 20 by default. 

@stefanprodan and @alexellis  if this sounds reasonable, I will open a PR.  This seems like something we could easily unit test, like we do for the `ReadOnlyRootFilesystem`.

**Comment by alexellis** [comment]
I'm curious as to why this isn't working as per the other providers.

Is this due to the use of the CRD vs the API?

@LucasRoesler please go ahead with whatever you feel would be the best fix. 

Alex

**Comment by alexellis** [comment]
This is how it's done in faas-swarm: https://github.com/openfaas/faas-swarm/blob/master/handlers/deploy.go#L339

Alex

**Comment by LucasRoesler** [comment]
The bug is that the replica labels are not respected at all in the reconciliation loop, it just doesn't exist.  The api submits and the data is there, but it is ignored except for during the "apply" command

**Comment by alexellis** [comment]
I think this is partially caused by the additional option of specifying an initial replica count. This doesn't really align well with the existing operating model where picking a min replica count is done through the scaling label.

We need to come up with a priority order if we want to keep that field and have it set the min replica count for scaling too.

**Comment by jpds** [comment]
In the normal Kubernetes deployment/HPA model, the replicas value set on the deployment is ignored by the HPA and governed by the latter instead.

```
$ kubectl get hpa -n nginx-ingress
NAME                       REFERENCE                             TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
nginx-ingress-controller   Deployment/nginx-ingress-controller   60%/90%, 1%/50%   3         6         3          17h
```
