### ISSUE TITLE
Update artifacts YAML

### ISSUE THREAD

**Issue by charles-d-burton** [openfaas/openfaas-operator#88]
The artifacts directory yaml files are way out of date, the pod definitions are pretty old and perhaps the other definitions are over.
## Expected Behaviour
Should be able to deploy from the artifacts directory.

## Current Behaviour
Does not deploy, image pull errors.

## Possible Solution
Update the yaml files

## Steps to Reproduce (for bugs)
kubectl apply -f artifacts/operator-armhf.yaml

## Context
We don't use helm, it has way too many issues around state management and cleanup for it work correctly so we rely on yaml files.
## Your Environment
Arm64 servers
Containerd

* What version and distriubtion of Kubernetes are you using? `kubectl version`
v1.14.5
* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 18.04

* What network driver are you using and what CIDR? i.e. Weave net / Flannel
Flannel

**Comment by alexellis** [comment]
Hi @charles-d-burton 

The operator is not being supported at this time for ARM64 due to lack of interest.

You can use faas-netes on ARM64, with the helm config, or feel free to submit a PR to update the YAML files you found here.

Cheers,

Alex

**Comment by alexellis** [comment]
@stefanprodan + @LucasRoesler 

I've deleted the armhf YAML file, but can you please update the amd64 artifact for the operator? Do we even need this anymore, given that it can be generated by the helm chart?

https://github.com/openfaas-incubator/openfaas-operator/blob/master/artifacts/operator-amd64.yaml

**Comment by LucasRoesler** [comment]
I don't think it is needed

**Comment by alexellis** [comment]
I think people use it to test the operator on its own..

**Comment by charles-d-burton** [comment]
Hey sorry, I didn't see the messages go by.  I can fix/update the yaml files for ARM64 pretty easily, I'm also fine using the helm templated files but I don't use helm mostly because running it in production is a special kind of nightmare.  If it's more useful I have a pattern for building Go apps that use Docker manifests to manage the arch under a single tag which lets Kubernetes make the decision about which arch to use.

**Comment by LucasRoesler** [comment]
would it be reasonable to generate it from the latest helm release instead of hand grooming these?

**Comment by alexellis** [comment]
@charles-d-burton can you use `helm template` to avoid your "special nightmare"? 😄

**Comment by alexellis** [comment]
@LucasRoesler anything required on this? If not, please close out.

**Comment by LucasRoesler** [comment]
As of today, i think these are updated now
